# Use an official Node.js runtime as a parent image
FROM node:latest

# Set the working directory in the container
WORKDIR /frontend

# Copy the current directory contents into the container at /frontend
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy the rest of the frontend files
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run npm start when the container launches
CMD ["npm", "start"]
