networks:
  app-network:
    driver: bridge

services:
  backend:
    networks:
      - app-network
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    working_dir: /app
    command: npm run start

  frontend:
    networks:
      - app-network
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
      - PUBLIC_URL=http://localhost:3000
    working_dir: /app
    command: npm start

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: huydukenguyen
      MONGO_INITDB_ROOT_PASSWORD: u923bmS996yzo50g
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: